name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - run: git submodule update --init --recursive

      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.6.13

      - id: git-sha-short-cosmos-chain-directory
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - id: git-sha-short-chain-registry
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        working-directory: chain-registry

      - name: build
        run: earthly --ci +build

      - name: Log in to the Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push docker image
        run: earthly --ci --push +docker --COSMOS_CHAIN_DIRECTORY_VERSION=${{ steps.git-sha-short-cosmos-chain-directory.outputs.sha_short }} --CHAIN_REGISTRY_VERSION=${{ steps.git-sha-short-chain-registry.outputs.sha_short }}

  deploy:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - uses: actions/checkout@v3

      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.6.13

      - id: git-sha-short-cosmos-chain-directory
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: deploy
        run: earthly --ci --secret GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" --secret AKASH_WALLET_KEY="${{ secrets.AKASH_WALLET_KEY }}" --secret AKASH_WALLET_KEY_PASSWORD="${{ secrets.AKASH_WALLET_KEY_PASSWORD }}" --secret AKASH_DEPLOY_CERTIFICATE="${{ secrets.AKASH_DEPLOY_CERTIFICATE }}" +deploy-to-akash --AKASH_DSEQ=${{ secrets.AKASH_DSEQ }} --AKASH_PROVIDER=${{ secrets.AKASH_PROVIDER }} --COSMOS_CHAIN_DIRECTORY_VERSION=${{ steps.git-sha-short-cosmos-chain-directory.outputs.sha_short }}